version: '3.2'
services:

  database:
    container_name: directus_db
    image: postgres:12
    restart: unless-stopped
    volumes:
      - ${DB_LOCATION}:/var/lib/postgresql/data
    networks:
      - ${NETWORK}
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

  pgadmin4:
    container_name: directus_pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - ${PGADMIN_LOCATION}:/var/lib/pgadmin
    ports:
      - ${PGADMIN_PORT}:80
    networks:
      - ${NETWORK}
    tty: true
    depends_on:
      - database
    links:
      - database

  cache:
    container_name: directus_redis
    image: redis:6
    restart: unless-stopped
    networks:
      - ${NETWORK}
    ports:
      - ${REDIS_PORT}:6379

  directus:
    container_name: directus_app
    image: directus/directus:latest
    restart: unless-stopped
    volumes:
      - ${HOST_UPLOADS}:${STORAGE_LOCAL_ROOT}
    ports:
      - ${DIR_PORT}:8055
    networks:
      - ${NETWORK}
    environment:
      LOG_LEVEL: ${LOG_LEVEL}

      KEY: ${DIR_KEY}
      SECRET: ${DIR_SECRET}

      DB_CLIENT: ${DB_CLIENT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      CACHE_ENABLED: ${CACHE_ENABLED}
      CACHE_STORE: ${CACHE_STORE}
      CACHE_REDIS: redis://cache:${REDIS_PORT}

      STORAGE_LOCATIONS: ${STORAGE_LOCATIONS}
      #STORAGE_LOCAL_PUBLIC_URL: ${STORAGE_LOCAL_PUBLIC_URL}
      STORAGE_LOCAL_DRIVER: ${STORAGE_LOCAL_DRIVER}
      STORAGE_LOCAL_ROOT: ${STORAGE_LOCAL_ROOT}

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      
#      EMAIL_FROM: no-reply@directus.io #Email address from which emails are sent. Default: `no-reply@directus.io`
#      EMAIL_TRANSPORT: smtp  #What to use to send emails. One of `sendmail`, `smtp`. Based on the transport used, you must also provide the following configurations.
#      Sendmail (sendmail):
#      EMAIL_SENDMAIL_NEW_LINE: unix # — What new line style to use in sendmail. Default: unix
#      EMAIL_SENDMAIL_PATH: /usr/sbin/sendmail # — Path to your sendmail executable. Default: /usr/sbin/sendmail
#      SMTP (smtp)
#      EMAIL_SMTP_HOST: #— SMTP Host
#      EMAIL_SMTP_PORT: #— SMTP Port
#      EMAIL_SMTP_USER: #— SMTP User
#      EMAIL_SMTP_PASSWORD: #— SMTP Password
#      EMAIL_SMTP_POOL: #— Use SMTP pooling
#      EMAIL_SMTP_SECURE: #— Enable TLS


networks:
  directus:
